// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmg_aClHW5OKjQ-CQNYUk3SkZ7WJ_-9Wg',
    appId: '1:801099113858:web:1ff6b7ae790350efbbdb9b',
    messagingSenderId: '801099113858',
    projectId: 'trucking-100-5223c',
    authDomain: 'trucking-100-5223c.firebaseapp.com',
    storageBucket: 'trucking-100-5223c.firebasestorage.app',
    measurementId: 'G-RYSTWB41MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiI64eGvw7w5wD04JNe56SkcofINo0RpA',
    appId: '1:801099113858:android:5ff27fa7ceb7ef73bbdb9b',
    messagingSenderId: '801099113858',
    projectId: 'trucking-100-5223c',
    storageBucket: 'trucking-100-5223c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQbB7cER_BC9HFxO_4RpenHnVD-QgGO4',
    appId: '1:801099113858:ios:c4ccf2e836c12063bbdb9b',
    messagingSenderId: '801099113858',
    projectId: 'trucking-100-5223c',
    storageBucket: 'trucking-100-5223c.firebasestorage.app',
    iosBundleId: 'com.example.fuelRoute',
  );
}
